language: node_js
os:
  - linux
node_js:
  - "12"
cache:
  yarn: true
env:
  - TONIC_UI_REPO: github.com/trendmicro-frontend/styled-ui.git


before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn build
after_success:
  - cd ..
  - ls
  - git clone https://github.com/trendmicro-frontend/styled-ui.git .styled-ui > /dev/null 2>&1
  - cd .styled-ui
  - git checkout -B feature/tmicon
  - git merge master
  - cp -f ../test2/tmIconMap.js ./packages/react-styled-ui/src/Icon/tmIconMap.js
  - git status
  - git add ./packages/react-styled-ui/src/Icon/tmIconMap.js
  - git commit -m 'core\:update tmicon'
  - git log