language: node_js
os:
  - linux
node_js:
  - "12"
cache:
  yarn: true
env:
  - TONIC_UI_REPO: github.com/trendmicro-frontend/styled-ui.git


before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn build
after_success:
  - cd ..
  - git clone https://github.com/trendmicro-frontend/styled-ui.git .styled-ui > /dev/null 2>&1
  - cd .styled-ui
  - git checkout -B feature/tmicon
  - git merge master
  - cp -f ../tmicon/tmIconMap.js ./packages/react-styled-ui/src/Icon/tmIconMap.js